### PR TITLE
Organize shell script to keep things easy to understand

### PR DESCRIPTION
**Pull request by idmarjr**
- bootstrap.sh -> vagrant-machine-setup.sh
- Organize and separate with ‘comment headers’ each thing and dependency installed during the provision.
- Add build-essential;
- Add git-core (Commented by default);
- Add imagemagick (Commented by default);
- Add nodejs;
- Add nodejs-legacy;
- Add npm;
- Add coffee-script;
- Add bower;
- Add Sass;
- Download and install last stable version of Redis;
- Add MongDB;
- Add - mongodb-clients;
- Show “Provision VM summary" in the end of provision;
- Add vagrant-machine-run.sh and set it to run always.

### CODE REVIEW

**Comment by micmro** [comment]
Great. Thanks. Can you fix the merge conflicts so I can merge it?

**Comment by idmarjr** [comment]
Sure @micmro :smile: 
I'm actually getting some issues with mongoDB right now. I will fix it first, fix all conflicts and than I let you know.

**Comment by idmarjr** [comment]
@micmro MongoDB installation is commented right now. I will need some extra time to figure out what is happening. If you're ok with miss MongoDB installation for a while, feel free to approve this pull request. :blush:

**Comment by micmro** [comment]
Works for me! Thanks!

**Pull request merged**
