### PR TITLE
Install last version of NodeJS, CoffeeScript and MongoDB

### PR DESCRIPTION
**Pull request by idmarjr**
- Install NodeJS v4.x;
- Install CoffeeScript via NPM (v1.10.0 at the time of this pull request);
- Install MongoDB v3.x;
- Keep paths export with it’s respective related installation;
- Organize Provision Summary;

### CODE REVIEW

**Comment by micmro** [comment]
Great - thanks!

**Comment by idmarjr** [comment]
@micmro I saw your suggestion here https://github.com/micmro/Vagrant-play/pull/3#issuecomment-139840430 and start to think about it.

Can you open a branch and make an example of how you image this variable structure to allow each installation? I like a lot of the idea but I'm not sure how to implement it. :pensive:

**Comment by micmro** [comment]
Thanks a lot for helping out! I did try to think about it but was than thinking it might make the structure harder than just commenting things out :). Will need  a bit time to think what would be better - either way works anyway.

**Comment by idmarjr** [comment]
That is exactly what I was thinking after a few reflection. This way we will have a elegant solution but it will increase a lot the complexity of it. Maybe have all installations commented by default is a good solution (Actually, Vagrant already work this way. :laughing: )

**Pull request merged**
